### ISSUE TITLE
Example for adobe air crash on android devices

### ISSUE THREAD

**Issue by novacoder** [Pushwoosh/pushwoosh-adobe-air#1]
I changed all required data in the example config to my own (app pakage name, PW_APPID, PW_PROJECT_ID) and it doesnt work on android devices. App crashes in 30 seconds after app run.

Tested on Nexus 4 (android 5.1.1) and THL T200 (android 4.2.2).

I noticed the pw_appid format in the example config is incorrect (4F0C807E51EC77.93591449) due to I have pw id in format to one that is used in iOs section in the example (539E9-AB8AE).

It works properly on iOS devices.

**Comment by shaders** [comment]
The new ANE version that fixes the crash published
