### ISSUE TITLE
Adobe Air - Pushwoosh ANE 1.5.0: extCtx is null. (iOS)

### ISSUE THREAD

**Issue by morscad** [Pushwoosh/pushwoosh-adobe-air#11]
I am using Air v.23, tried it on iOS 8.4.1 and on iOS 10.2.1
using the ANE and the SWC from the latest github push (downloaded today)
and I am getting this error:
```
extCtx is null.
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at com.pushwoosh.nativeExtensions::PushNotification/onDeviceReady()[/Volumes/workspace/workspace/pushwoosh-publish-adobe-air/ANE-Pushwoosh-src/actionscript/src/com/pushwoosh/nativeExtensions/PushNotification.as:122]
	at MedMobileFlex/callPushServices()[/Users/morscad/Documents/WORK/WEB/Design Is Yummy/MedMobile/MedMobileFlex/src/MedMobileFlex.mxml:154]
```

Didn't try Android yet.
help?

**Comment by morscad** [comment]
anyone?

**Comment by shaders** [comment]
Did you select to include the extension when you publish/build the app?

Also what platform this happens on?

**Comment by wfhm** [comment]
@morscad 

By any chance could you please provide a status update on this issue? Can you reproduce it with the latest plugin version?

**Comment by morscad** [comment]
This was fixed with the latest ANE and ANT compile. you need to update your AIR SDK and your app descriptor, and register the pushwoosh account with firebase for google also. I only tested the new set up on Android and it works, didn't try  iOS yet

**Comment by wfhm** [comment]
@morscad Thanks for the update!
