### ISSUE TITLE
Conflict with distriqt androidsupport.V4 ane. 

### ISSUE THREAD

**Issue by Pandan** [Pushwoosh/pushwoosh-adobe-air#12]
Hi,

I am using multiple ane's from Distriqt (distriqt.com)
It seems that their androidsupport (https://github.com/distriqt/ANE-AndroidSupport) ane have a conflict with the pushwoosh ane. 

I get this error:
dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Landroid/support/annotation/ColorRes;
at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
at com.android.dx.command.dexer.Main.processClass(Main.java:737)
at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
at com.android.dx.command.dexer.Main.access$300(Main.java:83)
at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)

This when using AIR SDK 25, and the following ane's (All updated to latest versions.)
com.pushwoosh.PushNotification
com.distriqt.Core
com.distriqt.androidsupport.V4

Any ideas on how to fix this?

**Comment by wfhm** [comment]
Hi,

Please refer to the guide below for a detailed instruction on resolving this conflict:

http://docs.pushwoosh.com/docs/resolving-google-play-services-conflicts#3-adobe-air

**Comment by Pandan** [comment]
Thx! 
I will try that. 
Or do you know if the android-support-v4 jar packed with pushwoosh is up to date?
If it is I guess I can remove com.distriqt.androidsupport.V4 and just use the one packed with pushwoosh.

**Comment by Pandan** [comment]
I managed to remove the android-support-v4 jar but when running the app with distriqt support ane the app crashes as soon as I try to register a device. 
Distriqt support ane is using android support jar r25.2.0 and the cameraroll ane that I am using is actually depending in some of the changes since r23. Could it be that pushwoosh somehow is depending on r23? And that's why I get a crash when removing it?

Is there any possible for you to update pushwoosh with a newer android support library. 
There have been a lot of updates including bug fixes to the lib since 23. 

Thanks

**Comment by wfhm** [comment]
> I managed to remove the android-support-v4 jar but when running the app with distriqt support ane the app crashes as soon as I try to register a device.

Could you please specify where from did you remove this jar (from PushNotification.ane or from any other source)? 

Also could you please provide a crash log?

**Comment by Pandan** [comment]
Hi, 
Everything was resolved. I am running the application without distriqt external android-support.ane and it seems to be working even though the support jar from pushwoosh is a bit behind. 
But it could be an enhancement for future releases, to have one version without the support jar and instead have a separate ane for that.
I know booth distriqt and myflashlabs is using this approach.

**Comment by wfhm** [comment]
Hi,

Good to hear it works now! We will discuss a possibility of having 2 separate versions with and without the lib.
