### ISSUE TITLE
Adobe Air - Android: device token empty

### ISSUE THREAD

**Issue by morscad** [Pushwoosh/pushwoosh-adobe-air#13]
my project suddenly stopped working (not receiving pushes) and my device token is always returning empty when I run the app. I have already migrated to google firebase per the instructions on the website.
I downloaded the sample project from this github to make sure that it's not my code, plugged my APP_ID and my senderID in the descriptor, and when I run the project in flash builder, I am getting this message:
`TOKEN error: Please set the mSenderId constant and recompile the app.`

specs: Adobe Air 27.0
Android 8.1.0

**Comment by wfhm** [comment]
Hi,

Could you please double-check which value  is set for the following meta-data in your XML:
```
<meta-data android:name="com.pushwoosh.senderid" android:value="SET_YOUR_SENDER_ID" />
```

Also, by any chance could you provide us with a full device log?

**Comment by morscad** [comment]
This is what I have
<meta-data android:name="com.pushwoosh.senderid" android:value="834466614855" />

I can't access my device log

**Comment by wfhm** [comment]
@morscad please try specifying it with an "A" prefix:

```
<meta-data android:name="com.pushwoosh.senderid" android:value="A834466614855" />
```

**Comment by morscad** [comment]
Confirmed. working when added A in front of the senderid
thanks
