### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by denyadanilov** [Pushwoosh/pushwoosh-adobe-air#14]
Good day!
I've updated PushWoosh ANE to the version 5.5.3 and I can't build application now. I've tried to build on Win and Mac both, result is the same. Using Itellij Idea, adobe adk 28, iOs sdk 11.2

It will be nice if you will point me to what I am doing wrong.

I receive the next message during package process:

Generating executable...
/Volumes/Work/SDKs/air-sdk-28/lib/aot/bin/ld64/ld64 -pie -ObjC -dead_strip -Z -arch armv7 -syslibroot "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk" -L/usr/lib -F"/System/Library/Frameworks" -L"/Volumes/Work/SDKs/air-sdk-28/lib/aot/lib" -o "../aot2193015749164496461.tmp" -exported_symbol _main "/Volumes/Work/SDKs/air-sdk-28/lib/aot/lib/libRuntimeHMAOT.arm-air.a" "/Volumes/Work/SDKs/air-sdk-28/lib/aot/lib/libNotification.arm-air.a" -lc++ -lSystem.B -lcrt1.o -lstdc++ -lz -lobjc -framework CoreFoundation -framework UIKit -framework MobileCoreServices -framework CoreGraphics -framework Foundation -framework SystemConfiguration -framework AudioToolbox -framework CFNetwork -framework QuartzCore -framework OpenGLES -framework CoreLocation -framework CoreMedia -framework CoreVideo -framework AVFoundation -framework Security -framework GameController -framework CoreMotion -framework AssetsLibrary -framework WebKit -framework StoreKit -framework Security -framework ImageIO -ObjC -exported_symbol _PushwooshExtInitializer -exported_symbol _PushwooshExtFinalizer -force_load "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/../../../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a" -filelist "/pushwoosh-adobe-air/PushNotificationsSample/bin-debug/AOTBuildOutput734566846094783354.tmp/OBJFilesList.txt" -ios_version_min 8.0 
Generating executable...
/Volumes/Work/SDKs/air-sdk-28/lib/aot/bin/ld64/ld64 -pie -ObjC -dead_strip -Z -arch arm64 -syslibroot "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk" -L/usr/lib -F"/System/Library/Frameworks" -L"/Volumes/Work/SDKs/air-sdk-28/lib/aot/lib" -o "../aot2304416727577730161.tmp" -exported_symbol _main "/Volumes/Work/SDKs/air-sdk-28/lib/aot/lib/libRuntimeHMAOT.arm-air.a" "/Volumes/Work/SDKs/air-sdk-28/lib/aot/lib/libNotification.arm-air.a" -lc++ -lSystem.B -lstdc++ -lz -lobjc -framework CoreFoundation -framework UIKit -framework MobileCoreServices -framework 
CoreGraphics -framework Foundation -framework SystemConfiguration 
-framework AudioToolbox -framework CFNetwork -framework QuartzCore 
-framework OpenGLES 
-framework CoreLocation -framework CoreMedia -framework CoreVideo -framework 
AVFoundation -framework 
Security -framework GameController -framework CoreMotion -framework 
AssetsLibrary -framework WebKit -framework StoreKit -framework Security 
-framework ImageIO -ObjC -exported_symbol 
_PushwooshExtInitializer -exported_symbol _PushwooshExtFinalizer -force_load "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/../../../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a" -filelist "/Volumes/Work/My_works/come2play/repos/BackgammonNew/libs/pushwoosh-adobe-air/PushNotificationsSample/bin-debug/AOTBuildOutput5885718497227145932.tmp/OBJFilesList.txt" -ios_version_min 8.0 
Undefined symbols for architecture arm64:
  "___isOSVersionAtLeast", referenced from:
      -[PWMessageViewController viewDidLoad] in libcom.pushwoosh.PushNotification.a(libPushwoosh.a-arm64-master.o)
ld: symbol(s) not found for architecture arm64
Undefined symbols for architecture armv7:
  "___isOSVersionAtLeast", referenced from:
com.adobe.air.ipa.ProcessError: Unable to generate executable
	at com.adobe.air.ipa.AOTCompiler.launchProcess(AOTCompiler.java:290)
	at com.adobe.air.ipa.AOTCompiler.linkMachO(AOTCompiler.java:758)
	at com.adobe.air.ipa.AOTCompiler.generateMachineBinaries(AOTCompiler.java:902)
	at com.adobe.air.ipa.IPAOutputStream.createIosBinary(IPAOutputStream.java:676)
	at com.adobe.air.ipa.IPAOutputStream.access$100(IPAOutputStream.java:91)
	at com.adobe.air.ipa.IPAOutputStream$CompileTask.run(IPAOutputStream.java:1570)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
      -[PWMessageViewController viewDidLoad] in libcom.pushwoosh.PushNotification.a(libPushwoosh.a-armv7-master.o)
ld: symbol(s) not found for architecture armv7
com.adobe.air.ipa.ProcessError: Unable to generate executable
	at com.adobe.air.ipa.AOTCompiler.launchProcess(AOTCompiler.java:290)
	at com.adobe.air.ipa.AOTCompiler.linkMachO(AOTCompiler.java:758)
	at com.adobe.air.ipa.AOTCompiler.generateMachineBinaries(AOTCompiler.java:902)
	at com.adobe.air.ipa.IPAOutputStream.createIosBinary(IPAOutputStream.java:676)
	at com.adobe.air.ipa.IPAOutputStream.access$100(IPAOutputStream.java:91)
	at com.adobe.air.ipa.IPAOutputStream$CompileTask.run(IPAOutputStream.java:1570)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Compilation failed while executing : ld64

ADT command line:
/Applications/IntelliJ IDEA.app/Contents/jdk/Contents/Home/jre/bin/java -Dapplication.home=/Volumes/Work/SDKs/air-sdk-28 -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.language=en -Duser.region=en -Xmx2048m -jar /Volumes/Work/SDKs/air-sdk-28/lib/adt.jar -package -Xverbose -target ipa-debug -listen 7936 -storetype PKCS12 -keystore ******* -storepass ******* -provisioning-profile ******** /PushNotificationsSample/bin-debug/Unnamed.ipa /PushNotificationsSample/bin-debug/TestPushNotifications-app.xml -platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -extdir /PushNotificationsSample/ANE-Pushwoosh -C /PushNotificationsSample/bin-debug TesPushWoosh.swf -C /PushNotificationsSample/src assets

**Comment by wfhm** [comment]
Hi,

This one is fixed in 5.5.4. Could you please try it and let us know about the results?

**Comment by denyadanilov** [comment]
Hi,
Thank you, everything works well now
