### ISSUE TITLE
PushWoosh ANE interferes with DISTRIQT Android Support V4 ANE

### ISSUE THREAD

**Issue by dgurney75** [Pushwoosh/pushwoosh-adobe-air#15]
I get a bunch of Java errors when trying to use your ANE with the Distriqt android support V4 ANE which supports all of their Android ANE functionality. Please remove the references listed in the attached image.  If you can't then i guess i will have to start using OneSignal for pushes. [Thanks.[]
![screen shot 2018-04-20 at 4 11 17 pm](https://user-images.githubusercontent.com/8271407/39074157-e8fc276e-44b5-11e8-99f7-1cc724b548bb.png)

**Comment by wfhm** [comment]
Hey,

This is a known issue with most of third party libraries that use Google Play services and/or Android Support libraries. Please follow the guide below to resolve the conflict:

https://www.pushwoosh.com/docs/resolving-google-play-services-conflicts#section-3-adobe-air

In a nutshell, you should unzip the ANE, remove the conflicting libraries and "sew" the extension back.

**Comment by wfhm** [comment]
@dgurney75 Did you have a chance to try the solution above?
