### ISSUE TITLE
Issue with the pushes sent from the API

### ISSUE THREAD

**Issue by Nikos-Laskaridis** [Pushwoosh/pushwoosh-adobe-air#16]
When I use the latest ANE (5.9.0) in our app I cannot receive pushes sent from the API.

If the pushes have been sent from the control panel they are received normally.

Also, pushes are received if I use an older version of the ANE, e.g. the one of 30/8/2018.

The app is targeted to Android 26 and is compiled with Adobe Air 31.

Pushes seem to be sent correctly from the API since app versions with older ANE receive them while the ones with 5.9.0 do not.

Please advise.

**Comment by wfhm** [comment]
@Nikos-Laskaridis 

This is very strange. By any chance could you please provide us with your /createMessage request body for undelivered messages? Also, please share your device log with a moment of expected push reception captured in it.

**Comment by wfhm** [comment]
@Nikos-Laskaridis any updates on the issue?

**Comment by wfhm** [comment]
Closed until there's more information to work with.
