### ISSUE TITLE
Pushwoosh ANE conflicts with distriqt ANEs

### ISSUE THREAD

**Issue by Nikos-Laskaridis** [Pushwoosh/pushwoosh-adobe-air#17]
Hi

I'm using the Pushwoosh ANE for a while and now I am facing an issue.
I have to use the distriqt Android Support ANE plus the distriqt playservices ANEs and they conflict with the Pushwoosh ANE.
I tried to remove the common libraries from Pushwoosh but unfortunately the result is an unstable app where the push services do not work.
Even if I would make it work somehow, I should have to repeat this procedure for every ANE update.
It would be very helpful to be able to use a Pushwoosh ANE without these common libraries.

**Comment by wfhm** [comment]
@Nikos-Laskaridis Could you please confirm that your issue was resolved via communication with our Support Team?
