### ISSUE TITLE
ane size

### ISSUE THREAD

**Issue by spanvega** [Pushwoosh/pushwoosh-adobe-air#2]
what's wrong with the ANE size, is it not a release version ?
Former version i have used was 1,4 Mb and this one 14 Mb, final apk size increased from 400Kb to 9Mo and getting the app compiled is just too long.

other few questions
1)  what are the detailed parameters for scheduleLocalNotification alertJson string

2)  is the feature 'Pass additional Custom Data to the app' when publishing a notification from the pushwoosh website no longer a free option ?

**Comment by shaders** [comment]
Latest Google Play Services library are just enormous in size and takes a lot to link.

Take a look on the scheduleLocalNotification example:
 
       pushwoosh.scheduleLocalNotification(30, "{\"alertBody\": \"Time to collect coins!\",
            \"alertAction\":\"Collect!\", \"soundName\":\"sound.caf\", \"badge\": 5, \"custom\": {\"a\":\"json\"}}");

On Android alertAction, soundName and badge would be ignored.

**Comment by spanvega** [comment]
thanks for the quick feedback, local and distant notifications are well dispatched, but could it be possible to add some events to handle them when application is running, since in that case no event is dispatched
