### ISSUE TITLE
Android X support

### ISSUE THREAD

**Issue by dgurney75** [Pushwoosh/pushwoosh-adobe-air#21]
The app crashes on launch when publishing from Adobe Animate using AIR 33.1.1.98. I noticed that the repo is still using the android.support libraries. I've updated those ANe's and still no luck. Does the pushNotification.ane still need to be updated as well?

**Comment by dgurney75** [comment]
Once i add the manifest code, that seems to cause the problem. Here is the xml.


[example-app.txt](https://github.com/Pushwoosh/pushwoosh-adobe-air/files/4594498/example-app.txt)

**Comment by wfhm** [comment]
@dgurney75 checking it.

**Comment by marchbold** [comment]
@dgurney75 If you need a temporary fix I can migrate the current ANE to AndroidX for you, no guarantees but I can run it through our conversion process.

**Comment by dgurney75** [comment]
That would be great.

________________________________

**Comment by marchbold** [comment]
I've just run this through our AndroidX converter

https://www.dropbox.com/s/c4jy5g5sqd3v1nv/ANE-Pushwoosh-androidx.zip?dl=0

Haven't tested it at all but see how it goes.

**Comment by dgurney75** [comment]
Thanks for trying, but still crashing at startup. Looking forward to the fix. Let me know if I can help in any way.

**Comment by marchbold** [comment]
Could you tell me what the crash is? Post the logs from the device when launching, you may just be missing a dependency?

**Comment by dgurney75** [comment]
05-12 09:14:10.976  9994  9994 E AndroidRuntime: FATAL EXCEPTION: main
05-12 09:14:10.976  9994  9994 E AndroidRuntime: Process: air.com.maritz.lexusEnCompass, PID: 9994
05-12 09:14:10.976  9994  9994 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/FirebaseApp;
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at com.pushwoosh.nativeExtensions.PushwooshFirebaseInitProvider.initFirebaseApp(PushwooshFirebaseInitProvider.java:37)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at com.pushwoosh.nativeExtensions.PushwooshFirebaseInitProvider.onCreate(PushwooshFirebaseInitProvider.java:32)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2113)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2087)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7408)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6953)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6844)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:268)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7811)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
05-12 09:14:10.976  9994  9994 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.firebase.FirebaseApp

**Comment by dgurney75** [comment]
Does that help?

**Comment by dgurney75** [comment]
<extensionID>com.distriqt.playservices.Base</extensionID>
        <extensionID>com.pushwoosh.PushNotification</extensionID>
        <extensionID>androidx.recyclerview</extensionID>
        <extensionID>androidx.appcompat</extensionID>
        <extensionID>com.google.android.material</extensionID>
        <extensionID>androidx.core</extensionID>
        <extensionID>com.distriqt.Firebase</extensionID>
        <extensionID>androidx.cardview</extensionID>

Those are the ANE's that are included.

**Comment by marchbold** [comment]
Are you using the latest release of our Firebase ANE? Then you'll need the common firebase dependency: [`com.google.firebase.core`](https://github.com/distriqt/ANE-GooglePlayServices/raw/master/lib/com.google.firebase.core.ane)

**Comment by dgurney75** [comment]
When i use both firebase ANE's i get the error when publishing: dx tool failed:Error: Program type already present: com.google.firebase.analytics.connector.AnalyticsConnector$AnalyticsConnectorListener
Compilation failed

**Comment by dgurney75** [comment]
<provider
                        android:name="com.pushwoosh.PushwooshInitProvider"
                        android:authorities="air.com.maritz.lexusEnCompass.pushwooshinitprovider"
                        android:enabled="true"
                        android:exported="false"
                        android:initOrder="50" />

                    <provider
                        android:name="com.pushwoosh.nativeExtensions.PushwooshFirebaseInitProvider"
                        android:authorities="air.com.maritz.lexusEnCompass.FirebaseInitProvider"
                        android:enabled="true"
                        android:exported="false"
                        android:initOrder="60" />

                    <provider
                        android:name="com.pushwoosh.PushwooshSharedDataProvider"
                        android:authorities="air.com.maritz.lexusEnCompass.PushwooshSharedDataProvider"
                        android:enabled="true"
                        android:exported="true"
                        android:initOrder="60"
                        />

Those lines in the manifest seem to causing the crash.

**Comment by marchbold** [comment]
Ah okay, you must still be using an old version of the Firebase ANE to get that "already present" error.

Prehaps try removing the `com.distriqt.Firebase` extension. I'm not really sure what they use out of it but most of the common dependencies should be in that `com.google.firebase.core` extension now.

**Comment by dgurney75** [comment]
Still getting same error when removing com.distriqt.Firebase extension. When i remove both extensions, it publishes but still crashes on startup. Those provider lines of code seem to cause the crash, but if i remove them, the push token never shows up.

**Comment by nikolleto** [comment]
@dgurney75, 

We have released our new ANE, please, check it out.
Pay attention to our updated integration guide https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/adobe-air

**Comment by dgurney75** [comment]
Works! Thanks for the support.
