### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by dgurney75** [Pushwoosh/pushwoosh-adobe-air#24]
Our company has been running security scans on all of our AIR apps and is flagging all Medium and High threats to be fixed. Here are the pdfs for the issues found with recommendations on how to address.

[pushWooshAirSecurity1.pdf](https://github.com/Pushwoosh/pushwoosh-adobe-air/files/6417344/pushWooshAirSecurity1.pdf)
[pushWooshAirSecurity2.pdf](https://github.com/Pushwoosh/pushwoosh-adobe-air/files/6417348/pushWooshAirSecurity2.pdf)
[pushWooshAirSecurity3.pdf](https://github.com/Pushwoosh/pushwoosh-adobe-air/files/6417349/pushWooshAirSecurity3.pdf)
[pushWooshAirSecurity4.pdf](https://github.com/Pushwoosh/pushwoosh-adobe-air/files/6417350/pushWooshAirSecurity4.pdf)

**Comment by wfhm** [comment]
@dgurney75,

Thanks for reporting this. We already have a task to address these vulnerabilities in our backlog. I will update this thread and ticket #58925 when there is any news.

**Comment by wfhm** [comment]
Fixed with the latest release.
