### ISSUE TITLE
PushNotification.ane has conflicts with other Distriqt ANEs

### ISSUE THREAD

**Issue by dgurney75** [Pushwoosh/pushwoosh-adobe-air#26]
I've been trying to upgrade several apps to meet the new Android 12 requirement and have been able to update most of the Distriqt ANEs without any issues. After adding just the PushNotification.ane file, I am getting conflicts stating that certain packages are being used by more than one ANE and I can't publish the APK without them being removed. 

I'm building the app in Adobe Animate (latest version) using AIR 33.1.1.929

Here's the errors I'm getting:

Warning: packagedDependency vectordrawable-animated-1.1.0.jar used by more than one ANE. Ignoring this entry
Warning: packagedDependency vectordrawable-1.1.0.jar used by more than one ANE. Ignoring this entry
Warning: packagedDependency tracing-1.0.0.jar used by more than one ANE. Ignoring this entry
Warning: packageName androidx.emoji2.viewsintegration used by more than one ANE. Ignoring this entry
Warning: packageName androidx.startup used by more than one ANE. Ignoring this entry
Warning: packageName androidx.emoji2 used by more than one ANE. Ignoring this entry

I don't have the knowledge to remove these myself and would appreciate some assistance.

Thanks,

Dan

**Comment by dgurney75** [comment]
If someone could tell me how to remove these libraries and re-package the ANE, I can do it myself. I've tried before and always have problems with the file not being recognized as an ANE any longer after removing the files form the META-INF folder and removing the instances from the platform.xml file. Not sure what i'm doing wrong. I'm on a Mac and would appreciate any help. Thanks!

**Comment by marchbold** [comment]
Hi, Is there an actual error? Those are all just warnings.

**Comment by dgurney75** [comment]
They are just warnings, but when trying to publish from Adobe Animate, it won't publish the APK when these warnings show up in the export. I don't know if this is a problem with AIR or Animate, but it would be great to know how to allow it to actually publish the APK if warnings don't mean anything.[](url)
![Screen Shot 2022-08-29 at 10 01 12 AM](https://user-images.githubusercontent.com/8271407/187232091-6ab93720-0692-4c39-9d59-0ad221e5f424.png)

**Comment by dgurney75** [comment]
This seems to do the trick. Might want to add this to your Tutorials if other devs need help modifying ANEs.

#!/bin/bash
WORKINGDIR=$(PWD)
TMPDIR=$WORKINGDIR/.tmp

ANEPATH=$WORKINGDIR/${1:-"out.ane"}
ANESOURCE=${2:-"."}
ZIP=zip

cd $ANESOURCE

$ZIP -rDq $ANEPATH mimetype -n swf:mimetype
$ZIP -rDq $ANEPATH META-INF/ANE/extension.xml -n swf:mimetype
$ZIP -rDq $ANEPATH catalog.xml -n swf:mimetype
$ZIP -rDq $ANEPATH library.swf -n swf:mimetype
$ZIP -rDq $ANEPATH META-INF -n swf:mimetype

cd $WORKINGDIR

Thanks!

**Comment by marchbold** [comment]
If the error doesn't display in the animate UI you can enable debug output from adt by setting `DebugOut=true` in `~/.airsdk/adt.cfg` (you may need to create this) or `AIRSDK/lib/adt.cfg`

You can then open up `~/adt.log` and see what the error is. 

There may have been one of the libs that had different versions to ours, which could have caused an error further down, but if you have just removed all the androidx libs from the push woosh ane that's probably the best idea :)
