### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by dgurney75** [Pushwoosh/pushwoosh-adobe-air#27]
I've traced the crash to these lines of code in the manifest file.

meta-data android:name="com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar"
android:value="com.google.firebase.components.ComponentRegistrar"

If I take those lines out, I never get the push token for the app.

**Comment by marchbold** [comment]
Probably missing some dependencies. Have you added the `com.google.firebase.core` extension? 

https://github.com/distriqt/ANE-GooglePlayServices/blob/master/lib/com.google.firebase.core.ane

**Comment by dgurney75** [comment]
Yes, I have. I have installed all of the latest dependencies from apm.

**Comment by marchbold** [comment]
Could you post the contents of the log when the crash occurs?
