### ISSUE TITLE
Events dispatched

### ISSUE THREAD

**Issue by spanvega** [Pushwoosh/pushwoosh-adobe-air#3]
local and distant notifications are well dispatched and handled when application is closed, but could it be possible to add some events to handle them when application is running, since in that case no event is dispatched

**Comment by shaders** [comment]
Is it iOS or Android?

**Comment by spanvega** [comment]
hi, i use it for an android app

**Comment by shaders** [comment]
Try to add to AndroidManifest (manifestAdditions section in -app.xml file):

    <meta-data android:name="PW_BROADCAST_PUSH" android:value="true" />

**Comment by spanvega** [comment]
that directive is in my application.xml, since i wrote it following the example provided with the ane

but is the ane supposed to catch them, PushNotificationEvent only handles 3 events ?

**Comment by shaders** [comment]
> but is the ane supposed to catch them, PushNotificationEvent only handles 3 events ?

http://s2.quickmeme.com/img/f7/f71beaed2b2a0d18a081fe28448c68ec43cc052c8c1539addfdaeede78e59800.jpg
