### ISSUE TITLE
Errors when building app with AIR 20

### ISSUE THREAD

**Issue by cchilds** [Pushwoosh/pushwoosh-adobe-air#4]
I am needing to update my AIR application from AIR 17 to AIR 20 to get some important bug fixes. After doing so, I can no longer build an iOS version of my app. I get the following error every time I try:

`Undefined symbols for architecture arm64:
  "_CGImageSourceCreateWithData", referenced from:
      ___72-[PWNetworkOperation decompressedResponseImageOfSize:completionHandler:]_block_invoke in C:\Users\cchilds\AppData\Local\Temp\822ea487-b9e7-4855-8eec-4208f176a533\libcom.pushwoosh.PushNotification.a(PWNetworkOperation.o)
  "_kCGImageSourceShouldCache", referenced from:
      ___72-[PWNetworkOperation decompressedResponseImageOfSize:completionHandler:]_block_invoke in C:\Users\cchilds\AppData\Local\Temp\822ea487-b9e7-4855-8eec-4208f176a533\libcom.pushwoosh.PushNotification.a(PWNetworkOperation.o)
  "_CGImageSourceCreateImageAtIndex", referenced from:
      ___72-[PWNetworkOperation decompressedResponseImageOfSize:completionHandler:]_block_invoke in C:\Users\cchilds\AppData\Local\Temp\822ea487-b9e7-4855-8eec-4208f176a533\libcom.pushwoosh.PushNotification.a(PWNetworkOperation.o)
ld: symbol(s) not found for architecture arm64
Undefined symbols for architecture armv7:
  "_kCGImageSourceShouldCache", referenced from:
      ___72-[PWNetworkOperation decompressedResponseImageOfSize:completionHandler:]_block_invoke in C:\Users\cchilds\AppData\Local\Temp\822ea487-b9e7-4855-8eec-4208f176a533\libcom.pushwoosh.PushNotification.a(PWNetworkOperation.o)
  "_CGImageSourceCreateWithData", referenced from:
      ___72-[PWNetworkOperation decompressedResponseImageOfSize:completionHandler:]_block_invoke in C:\Users\cchilds\AppData\Local\Temp\822ea487-b9e7-4855-8eec-4208f176a533\libcom.pushwoosh.PushNotification.a(PWNetworkOperation.o)
  "_CGImageSourceCreateImageAtIndex", referenced from:
      ___72-[PWNetworkOperation decompressedResponseImageOfSize:completionHandler:]_block_invoke in C:\Users\cchilds\AppData\Local\Temp\822ea487-b9e7-4855-8eec-4208f176a533\libcom.pushwoosh.PushNotification.a(PWNetworkOperation.o)
ld: symbol(s) not found for architecture armv7
Compilation failed while executing : ld64`

Looking around the internet, it appears as though this is possibly caused by not linking the ImageIO.framework when packaging the ANE. Any help would be greatly appreciated. Thanks

**Comment by DimanAM** [comment]
AIR SDK 20.0 is broken. Just replace ImageIO.framework in <AIRSDK>/lib/aot/stub with <Xcode.app>/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/<iOS_SDK>/System/Library/Frameworks/ImageIO.framework

**Comment by shaders** [comment]
Yes, that's a known bug of Adobe: https://forums.adobe.com/thread/2041879?start=0&tstart=0
Other option would be copying ImageIO.framework from AIR SDK 19 to SDK 20

**Comment by cchilds** [comment]
Copying over the framework from AIR 19 worked great. Thanks so much for the help, you guys are the best!
