### ISSUE TITLE
Issues publishing with Air 20 and 21

### ISSUE THREAD

**Issue by dgurney75** [Pushwoosh/pushwoosh-adobe-air#5]
I was publishing using Adobe Air 19 with no problems, but when I moved to 20, i get an error "Invalid Input" and just stops publishing. Any thoughts?

**Comment by shaders** [comment]
Maybe this could help? https://github.com/Pushwoosh/pushwoosh-adobe-air/issues/4

**Comment by BenLeffler** [comment]
I can confirm that the solution outlined in ticket 4 as per @shaders comment does indeed fix this issue. Wish I had of found this thread 3 days ago though!
